language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - yarn test
  - yarn build
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_TOKEN
  app: temp_heroku_travis # to be replaced
  on:
    repo: davified/temp_heroku_travis   # to be replaced

