language: node_js
node_js:
- '9'
cache:
  directories:
  - node_modules
script:
- yarn test
- yarn build
deploy:
  provider: heroku
  api_key:
    secure: TPzSbjFmtvfZNAhcvZrWXKQhjuWTFgaAV6sgdo59W0uc/VA5B2V6RVPeO8aFIeP2m1OWC0dnasiL89bE2MPNSWe9hswkUecjYRx2dGhrs2tYcNyKCsL1SrGjNTLLNe+1aPpzUctF2aWqid0w00iQjge47DiGFJbHnr/q2GBn5N40iVu3CHDD72gQdkulFINH3Ea2OTtFOz0RKTIHs+DhbpqWudICozcGzR81HTLnvKh4QPFFCss3WAvmZlFObgHLhE6iYpNDeW6rgJB5nxpoFHhoiZrQD6D7L2U/ZzyAvcAk0PfvPvZtFIM07x8KdSh2Bk1iYuOzKENXTn1cN8/FzOOtPAEQ1PwJCG+/yWG8y7RVdi7vl0dR+TUHMzK/x/C2o7NoL8AsZc7V82b1Vudiw/0ISoiLegeGo5sO9Plisr1rmpBZgMJQPLuDqyiTPFQrPnjakjeUvHKwrt5ef5jT+e2dork8vIfey0lBNtdlYW0I93aQDx7fF/OrFAHc5a3eV1NcjV87OBK/2T/wPPPPRUFd+wc935DnTnAlnp97KXK2rhCZ6wQv+1ZwZPRUwPK7CN+Yt8Gkm+UvLPRScltJDkUmoMJS9u/eB6P8LKYWvBIR8f7kB7lGmOpJR+pbS5M/NbqcdNEaZswgubcLs40XuVmhAmab0KRUOaWGRp9+r2w=
  app: rocky-everglades-35084
  on:
    repo: davified/temp_heroku_travis
